spring:
  application:
    name: spring-cloud-provider
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    healthcheck:
      enabled: true #为开启健康检查