spring:
  application:
    name: service-zuul-simple
#  zipkin:
#    base-url: http://localhost:9100
#  sleuth:
#    sampler:
#      percentage: 1.0
server:
  port: 8888
#zuul:
#  routes:
#    api-a.path: /provider/**
#    api-a.serviceId: spring-cloud-provider
# 注释掉路由配置以启动默认路由规则 http://ZUUL_HOST:ZUUL_PORT/微服务在Eureka上的serviceId/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/