server:
  port: 8001
spring:
  application:
    name: git-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/littlecarzz/spring-cloud/ # 配置git仓库的地址
          search-paths: config-repo # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: littlecarzz
          password: zaoanchs1130