spring:
  application:
    name: service-zuul-simple
server:
  port: 8888
zuul:
  routes:
    baidu:
      path: /it/**
      url: http://www.ityouknow.com/
    hello:
      path: /hello/**
      url: http://localhost:9000/